server:
  port: 0

spring:
  application:
    name: my-frist-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8760/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

